### ISSUE TITLE
Error with definition.py

### ISSUE THREAD

**Issue by DelphinPETER** [ubitux/cura-dagoma#1]
J'ai cette erreur avec definition.py, je suis novice en python du coup j'ai du mal à trouver ce qui ne marche pas : 
```
python3 definition.py input/discoeasy200/xml_config.xml output/discoeasy200/definitions/dagoma_discoeasy200.def.json
Traceback (most recent call last):
  File "definition.py", line 191, in <module>
    convert(*sys.argv[1:])
  File "definition.py", line 182, in convert
    extract_fields(o, section, config_expert_fields)
  File "definition.py", line 59, in extract_fields
    dst[field] = get_default_dict(section, dagoma_field, field_type)
  File "definition.py", line 34, in get_default_dict
    return {'default_value': field_type(xml_node.find(field_name).text)}
AttributeError: 'NoneType' object has no attribute 'text'
Makefile:20 : la recette pour la cible « definitions » a échouée
make: *** [definitions] Erreur 1
```

**Comment by ubitux** [comment]
Il ne trouve pas de node `field_name` dans le XML. Tu as fait des modifications à `definition.py` ou au XML ? Tu peux mettre un `print(field_name)` dans le `get_default_dict()` ?

**Comment by DelphinPETER** [comment]
Ok, c'est une erreur de ma part. J'ai complété les variables et j'ai inversé deux correspondances.
Désolé, je vous envoi un commit de ce que j'ai mis à jour.
